spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hcd_final?useSSL=false
    name: hcd_final
    username: root
    password: yz450f
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update   
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
         
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        use_sql_comments: true
        format_sql: true
        type: trace 
        
  thymeleaf:
    cache: false
  http:
    encoding:
      charset: UTF-8
logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder:TRACE